-- ============================================================
-- SQL Configuration — Aura Trade Moderation & Reviews System
-- Supabase → SQL Editor → Coller tout → Run
-- ============================================================

-- 1. Ajout des colonnes de modération à la table profiles
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS banned boolean NOT NULL DEFAULT false;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS banned_until timestamptz DEFAULT NULL;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS ban_reason text DEFAULT NULL;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS kick_token text DEFAULT NULL;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS pending_kick text DEFAULT NULL;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS pending_warning text DEFAULT NULL;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS can_view_logs boolean NOT NULL DEFAULT false;

-- Index sur les colonnes fréquemment requêtées pour la modération
CREATE INDEX IF NOT EXISTS profiles_banned_idx ON public.profiles (banned);

-- 2. Création de la table staff_logs (journaux d'action du staff)
CREATE TABLE IF NOT EXISTS public.staff_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id text NOT NULL,
    staff_pseudo text NOT NULL,
    action text NOT NULL,
    target_id text,
    details text,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Index sur les logs
CREATE INDEX IF NOT EXISTS staff_logs_action_idx ON public.staff_logs (action);
CREATE INDEX IF NOT EXISTS staff_logs_staff_id_idx ON public.staff_logs (staff_id);

-- Droits pour la table staff_logs (requis pour le client anonyme)
GRANT SELECT, INSERT ON public.staff_logs TO anon;
GRANT ALL ON public.staff_logs TO service_role;

-- RLS pour staff_logs
ALTER TABLE public.staff_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "allow insert staff_logs" ON public.staff_logs;
CREATE POLICY "allow insert staff_logs" 
    ON public.staff_logs FOR INSERT TO anon, authenticated 
    WITH CHECK (true);

DROP POLICY IF EXISTS "allow select staff_logs" ON public.staff_logs;
CREATE POLICY "allow select staff_logs" 
    ON public.staff_logs FOR SELECT TO anon, authenticated 
    USING (true);


-- 3. Création de la table reviews (avis reçus sur les joueurs)
CREATE TABLE IF NOT EXISTS public.reviews (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    from_user_id text NOT NULL,
    from_user_pseudo text NOT NULL,
    to_user_id text NOT NULL,
    rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment text,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Index sur les avis
CREATE INDEX IF NOT EXISTS reviews_to_user_id_idx ON public.reviews (to_user_id);
CREATE INDEX IF NOT EXISTS reviews_from_user_id_idx ON public.reviews (from_user_id);

-- Droits pour la table reviews
GRANT SELECT, INSERT, UPDATE, DELETE ON public.reviews TO anon;
GRANT ALL ON public.reviews TO service_role;

-- RLS pour reviews
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "allow insert reviews" ON public.reviews;
CREATE POLICY "allow insert reviews" 
    ON public.reviews FOR INSERT TO anon, authenticated 
    WITH CHECK (true);

DROP POLICY IF EXISTS "allow select reviews" ON public.reviews;
CREATE POLICY "allow select reviews" 
    ON public.reviews FOR SELECT TO anon, authenticated 
    USING (true);

DROP POLICY IF EXISTS "allow update reviews" ON public.reviews;
CREATE POLICY "allow update reviews" 
    ON public.reviews FOR UPDATE TO anon, authenticated 
    USING (true)
    WITH CHECK (true);

DROP POLICY IF EXISTS "allow delete reviews" ON public.reviews;
CREATE POLICY "allow delete reviews" 
    ON public.reviews FOR DELETE TO anon, authenticated 
    USING (true);

-- Rafraîchir le schéma d'API Supabase PostgREST
NOTIFY pgrst, 'reload schema';
